<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Company;
use App\Models\JobVacancy;
use App\Models\Major;
use App\Models\StandardType;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class JobVacancySeeder extends Seeder
{
    public function run(): void
    {
        DB::transaction(function (): void {
            $admin = User::where('role', 'admin')->first();
            $creatorId = $admin?->id ?? 1;

            $statusPublished = StandardType::byCategory('vacancy_status')->where('code', 'published')->first();
            $types = StandardType::byCategory('job_type')->pluck('id', 'code');
            $targets = StandardType::byCategory('target_applicant')->pluck('id', 'code');
            $companies = Company::pluck('id', 'name');
            $majorMap = Major::all()->keyBy('code');

            $vacancies = [
                [
                    'company' => 'PT Kejayaan Terraloka',
                    'target' => 'alumni_only',
                    'type' => 'full_time',
                    'position' => 'Estimator & Quantity Surveyor Junior',
                    'desc' => 'Menghitung volume pekerjaan konstruksi sipil, estimasi rencana anggaran biaya (RAB), dan evaluasi progress opname fisik bangunan.',
                    'qual' => "1. Khusus Alumni SMK jurusan Teknik Pemesinan / Konstruksi / Gambar Bangunan\n2. Mahir membaca gambar teknik CAD dan kalkulasi volume material\n3. Penempatan proyek Surabaya",
                    'quota' => 4,
                    'location' => 'Surabaya, Jawa Timur',
                    'min_salary' => 5200000,
                    'max_salary' => 6800000,
                    'featured' => true,
                    'majors' => ['TP', 'DKV'],
                ],
                [
                    'company' => 'PT Kejayaan Terraloka',
                    'target' => 'class_12_only',
                    'type' => 'internship',
                    'position' => 'Drafter CAD Bangunan Magang',
                    'desc' => 'Membantu pembuatan drafting gambar kerja 2D/3D untuk perumahan komersial dan revisi detail as-built drawing.',
                    'qual' => "1. Siswa aktif kelas 12 SMK jurusan Teknik Pemesinan atau Desain Bangunan\n2. Menguasai software AutoCAD dasar dan SketchUp\n3. Bersedia magang 6 bulan di Surabaya",
                    'quota' => 6,
                    'location' => 'Surabaya, Jawa Timur',
                    'min_salary' => 2500000,
                    'max_salary' => 3200000,
                    'featured' => false,
                    'majors' => ['TP', 'DKV'],
                ],
                [
                    'company' => 'PT Kejayaan Terraloka',
                    'target' => 'class_12_and_alumni',
                    'type' => 'contract',
                    'position' => 'Quality Control Proyek Lapangan',
                    'desc' => 'Melakukan supervisi pengecekan mutu material bangunan di lapangan dan dokumentasi checklist standar keselamatan K3 proyek.',
                    'qual' => "1. Siswa kelas 12 atau Alumni SMK jurusan Teknik Pemesinan / Konstruksi\n2. Teliti, disiplin, dan memiliki integritas pengawasan lapangan yang tinggi\n3. Siap ditempatkan di area proyek Surabaya dan sekitarnya",
                    'quota' => 5,
                    'location' => 'Surabaya, Jawa Timur',
                    'min_salary' => 4500000,
                    'max_salary' => 5500000,
                    'featured' => false,
                    'majors' => ['TP'],
                ],
                [
                    'company' => 'PT Hyperdata Solusindo Mandiri',
                    'target' => 'alumni_only',
                    'type' => 'full_time',
                    'position' => 'Junior Backend Web Developer',
                    'desc' => 'Mengembangkan dan merawat RESTful API performa tinggi menggunakan PHP Laravel, PostgreSQL, integrasi Redis, dan automated testing.',
                    'qual' => "1. Khusus Alumni SMK jurusan Rekayasa Perangkat Lunak (RPL)\n2. Memahami konsep MVC, ORM Eloquent, database relational, dan autentikasi token\n3. Memiliki portofolio backend project yang dapat dipresentasikan",
                    'quota' => 4,
                    'location' => 'Kota Malang, Jawa Timur',
                    'min_salary' => 5500000,
                    'max_salary' => 7500000,
                    'featured' => true,
                    'majors' => ['RPL'],
                ],
                [
                    'company' => 'PT Hyperdata Solusindo Mandiri',
                    'target' => 'class_12_only',
                    'type' => 'internship',
                    'position' => 'Junior Frontend Web Developer Magang',
                    'desc' => 'Membantu implementasi komponen antarmuka web modern menggunakan React, TypeScript, dan Tailwind CSS dalam tim agile sprint.',
                    'qual' => "1. Siswa aktif kelas 12 SMK jurusan Rekayasa Perangkat Lunak (RPL)\n2. Memahami semantic HTML5, CSS responsive layout, dan JavaScript ES6+\n3. Memiliki semangat belajar tinggi dan terbiasa menggunakan Git",
                    'quota' => 5,
                    'location' => 'Kota Malang, Jawa Timur',
                    'min_salary' => 2500000,
                    'max_salary' => 3500000,
                    'featured' => false,
                    'majors' => ['RPL'],
                ],
                [
                    'company' => 'PT Hyperdata Solusindo Mandiri',
                    'target' => 'class_12_and_alumni',
                    'type' => 'contract',
                    'position' => 'IT Support & Technical Specialist',
                    'desc' => 'Memberikan penanganan trouble ticketing aplikasi klien, instalasi lingkungan staging software, dan pemeliharaan server local office.',
                    'qual' => "1. Siswa kelas 12 atau Alumni SMK jurusan TKJ / RPL\n2. Memahami troubleshooting hardware, konfigurasi jaringan LAN, dan Linux OS dasar\n3. Komunikatif dan berorientasi pada kepuasan pengguna",
                    'quota' => 6,
                    'location' => 'Kota Malang, Jawa Timur',
                    'min_salary' => 4200000,
                    'max_salary' => 5200000,
                    'featured' => false,
                    'majors' => ['TKJ', 'RPL'],
                ],
                [
                    'company' => 'PT Bank Central Asia',
                    'target' => 'alumni_only',
                    'type' => 'full_time',
                    'position' => 'IT Application Operator & Service Desk',
                    'desc' => 'Melakukan monitoring kestabilan transaksi perbankan digital, penanganan eskalasi tiket insiden aplikasi kantor cabang, dan audit log operasional.',
                    'qual' => "1. Alumni SMK jurusan Rekayasa Perangkat Lunak (RPL) atau Teknik Komputer dan Jaringan (TKJ)\n2. Memiliki ketelitian tinggi dan kemampuan komunikasi koordinasi profesional\n3. Bersedia bekerja dalam pola sistem shift operasional",
                    'quota' => 5,
                    'location' => 'Jakarta Pusat, DKI Jakarta',
                    'min_salary' => 6000000,
                    'max_salary' => 8000000,
                    'featured' => true,
                    'majors' => ['RPL', 'TKJ'],
                ],
                [
                    'company' => 'PT Bank Central Asia',
                    'target' => 'class_12_only',
                    'type' => 'internship',
                    'position' => 'Magang Administrasi & Data Entry Operasional',
                    'desc' => 'Membantu verifikasi kelengkapan berkas nasabah, input data transaksi perbankan ke sistem internal, dan rekapitulasi arsip harian.',
                    'qual' => "1. Siswa kelas 12 aktif SMK jurusan Bisnis Digital & Pemasaran (BDP) atau RPL\n2. Mampu mengetik cepat, teliti, dan menguasai Microsoft Office / Spreadsheet\n3. Berpenampilan rapi dan mematuhi etika kerahasiaan data nasabah",
                    'quota' => 8,
                    'location' => 'Jakarta Pusat, DKI Jakarta',
                    'min_salary' => 2800000,
                    'max_salary' => 3600000,
                    'featured' => false,
                    'majors' => ['BDP', 'RPL'],
                ],
                [
                    'company' => 'PT Bank Central Asia',
                    'target' => 'class_12_and_alumni',
                    'type' => 'contract',
                    'position' => 'Customer Service & Branch IT Assistant',
                    'desc' => 'Melayani aktivasi layanan digital banking nasabah di banking hall serta asistensi pemeliharaan perangkat tablet/PC mesin self-service.',
                    'qual' => "1. Siswa kelas 12 atau Alumni SMK jurusan Bisnis Digital (BDP) / TKJ / RPL\n2. Ramah, berpenampilan rapi, memiliki kemampuan komunikasi publik yang prima\n3. Memahami penggunaan smartphone dan aplikasi mobile banking terkini",
                    'quota' => 6,
                    'location' => 'Surabaya, Jawa Timur',
                    'min_salary' => 4800000,
                    'max_salary' => 6000000,
                    'featured' => false,
                    'majors' => ['BDP', 'TKJ'],
                ],
                [
                    'company' => 'PT Perusahaan Listrik Negara',
                    'target' => 'alumni_only',
                    'type' => 'full_time',
                    'position' => 'Junior Electrical Substation Technician',
                    'desc' => 'Melakukan inspeksi berkala peralatan gardu induk tegangan tinggi, pemeliharaan trafo daya, pemutus tenaga (PMT), dan sistem proteksi relay.',
                    'qual' => "1. Khusus Alumni SMK jurusan Teknik Pembangkit Tenaga Listrik (PB) atau Elektronika Industri (EI)\n2. Memahami single line diagram listrik dan standar keselamatan ketenagalistrikan K3\n3. Tidak buta warna dan sehat jasmani untuk tugas lapangan",
                    'quota' => 4,
                    'location' => 'Jakarta Selatan, DKI Jakarta',
                    'min_salary' => 6200000,
                    'max_salary' => 8500000,
                    'featured' => true,
                    'majors' => ['PB', 'EI'],
                ],
                [
                    'company' => 'PT Perusahaan Listrik Negara',
                    'target' => 'class_12_only',
                    'type' => 'internship',
                    'position' => 'Magang Pemeliharaan Jaringan Distribusi',
                    'desc' => 'Praktik industri mendampingi tim regu pemeliharaan jaringan tegangan menengah (JTM) dan penggantian isolator tumpu di tiang distribusi.',
                    'qual' => "1. Siswa aktif kelas 12 SMK jurusan Teknik Pembangkit Tenaga Listrik (PB)\n2. Memperoleh surat rekomendasi magang resmi dari pihak sekolah SMK\n3. Disiplin tinggi terhadap penggunaan alat pelindung diri (APD)",
                    'quota' => 6,
                    'location' => 'Jakarta Selatan, DKI Jakarta',
                    'min_salary' => 2500000,
                    'max_salary' => 3500000,
                    'featured' => false,
                    'majors' => ['PB'],
                ],
                [
                    'company' => 'PT Perusahaan Listrik Negara',
                    'target' => 'class_12_and_alumni',
                    'type' => 'contract',
                    'position' => 'Teknisi Pengukuran & Meter Digital',
                    'desc' => 'Pemasangan kWh meter prabayar cerdas, kalibrasi alat ukur pembatas daya, dan pencatatan parameter konsumsi energi listrik pelanggan industri.',
                    'qual' => "1. Siswa kelas 12 atau Alumni SMK jurusan Teknik Pembangkit Listrik (PB) / Elektronika Industri (EI)\n2. Teliti membaca besaran listrik arus, tegangan, dan faktor daya\n3. Memiliki kendaraan bermotor pribadi dan SIM C aktif",
                    'quota' => 7,
                    'location' => 'Surabaya, Jawa Timur',
                    'min_salary' => 4600000,
                    'max_salary' => 5800000,
                    'featured' => false,
                    'majors' => ['PB', 'EI'],
                ],
                [
                    'company' => 'PT Telkom Indonesia',
                    'target' => 'alumni_only',
                    'type' => 'full_time',
                    'position' => 'Junior Fiber Optic & Network Engineer',
                    'desc' => 'Pemasangan kabel fiber optik backbone, penyambungan core dengan fusion splicer, analisa redaman optical time-domain reflectometer (OTDR).',
                    'qual' => "1. Alumni SMK jurusan Teknik Komputer dan Jaringan (TKJ)\n2. Memahami topologi FTTH, fungsi ODC/ODP, dan troubleshooting kabel optik\n3. Tidak takut ketinggian dan siap bertugas di posko operasional",
                    'quota' => 5,
                    'location' => 'Jakarta Selatan, DKI Jakarta',
                    'min_salary' => 5500000,
                    'max_salary' => 7200000,
                    'featured' => true,
                    'majors' => ['TKJ'],
                ],
                [
                    'company' => 'PT Telkom Indonesia',
                    'target' => 'class_12_only',
                    'type' => 'internship',
                    'position' => 'Magang Teknisi Akses Jaringan FTTH',
                    'desc' => 'Membantu teknisi senior instalasi kabel drop core ke pelanggan IndiHome, aktivasi Optical Network Terminal (ONT), dan tes konektivitas Wi-Fi.',
                    'qual' => "1. Siswa kelas 12 aktif SMK jurusan Teknik Komputer dan Jaringan (TKJ)\n2. Memahami dasar konfigurasi IP address, subnet mask, dan gateway router\n3. Bersedia mengikuti program magang selama 6 bulan penuh",
                    'quota' => 8,
                    'location' => 'Kota Malang, Jawa Timur',
                    'min_salary' => 2500000,
                    'max_salary' => 3200000,
                    'featured' => false,
                    'majors' => ['TKJ'],
                ],
                [
                    'company' => 'PT Telkom Indonesia',
                    'target' => 'class_12_and_alumni',
                    'type' => 'contract',
                    'position' => 'NOC Monitoring & Network Helpdesk',
                    'desc' => 'Memantau availability link jaringan internet korporasi melalui dashboard NMS, pencatatan tiket incident report, dan eskalasi gangguan link.',
                    'qual' => "1. Siswa kelas 12 atau Alumni SMK jurusan TKJ / RPL\n2. Memahami konsep routing switching, protokol TCP/IP, dan command line Mikrotik\n3. Bersedia bekerja dalam jadwal shift 24/7 secara bergantian",
                    'quota' => 6,
                    'location' => 'Jakarta Selatan, DKI Jakarta',
                    'min_salary' => 4800000,
                    'max_salary' => 6000000,
                    'featured' => false,
                    'majors' => ['TKJ', 'RPL'],
                ],
                [
                    'company' => 'PT Astra Honda Motor',
                    'target' => 'alumni_only',
                    'type' => 'full_time',
                    'position' => 'Operator Perakitan Mesin Sepeda Motor',
                    'desc' => 'Melakukan perakitan mesin presisi sepeda motor di jalur ban berjalan pabrik, pengencangan baut torsi terkalibrasi, dan pengujian akhir mesin.',
                    'qual' => "1. Khusus Alumni SMK jurusan Teknik Sepeda Motor (TSM), TKR, atau Teknik Pemesinan (TP)\n2. Fisik prima, tidak buta warna, tinggi badan proporsional sesuai standar manufaktur\n3. Disiplin tinggi terhadap target output lini produksi dan SOP K3",
                    'quota' => 15,
                    'location' => 'Jakarta Utara, DKI Jakarta',
                    'min_salary' => 5400000,
                    'max_salary' => 6600000,
                    'featured' => true,
                    'majors' => ['TSM', 'TKR', 'TP'],
                ],
                [
                    'company' => 'PT Astra Honda Motor',
                    'target' => 'class_12_only',
                    'type' => 'internship',
                    'position' => 'Magang Prakerin Teknisi Assembling Line',
                    'desc' => 'Program praktik kerja lapangan di lini perakitan sasis kendaraan, handling part logistik komponen mesin, dan asistensi teknisi perakitan.',
                    'qual' => "1. Siswa aktif kelas 12 SMK jurusan Teknik Sepeda Motor (TSM) atau TKR\n2. Memperoleh surat pengantar resmi dari BKK / sekolah SMK pengirim\n3. Sehat jasmani dan bersedia ditempatkan di pabrik Sunter / Karawang",
                    'quota' => 12,
                    'location' => 'Jakarta Utara, DKI Jakarta',
                    'min_salary' => 2800000,
                    'max_salary' => 3800000,
                    'featured' => false,
                    'majors' => ['TSM', 'TKR'],
                ],
                [
                    'company' => 'PT Astra Honda Motor',
                    'target' => 'class_12_and_alumni',
                    'type' => 'contract',
                    'position' => 'Quality Inspector Komponen Presisi',
                    'desc' => 'Melakukan pemeriksaan dimensi komponen casting dan stamping menggunakan jangka sorong, mikrometer sekrup, dan dial indicator presisi tinggi.',
                    'qual' => "1. Siswa kelas 12 atau Alumni SMK jurusan TSM / TP / TKR\n2. Menguasai alat ukur presisi metrologi mekanik hingga ketelitian 0.01 mm\n3. Cermat, teliti, dan tidak memiliki riwayat buta warna",
                    'quota' => 10,
                    'location' => 'Jakarta Utara, DKI Jakarta',
                    'min_salary' => 5200000,
                    'max_salary' => 6300000,
                    'featured' => false,
                    'majors' => ['TSM', 'TP'],
                ],
                [
                    'company' => 'PT United Tractors Tbk',
                    'target' => 'alumni_only',
                    'type' => 'full_time',
                    'position' => 'Junior Heavy Equipment Mechanic',
                    'desc' => 'Melaksanakan perawatan preventif unit alat berat excavator, bulldozer, dump truck, overhaul mesin diesel common rail, dan servis pompa hidrolik.',
                    'qual' => "1. Alumni SMK jurusan Teknik Kendaraan Ringan (TKR), Pemesinan (TP), atau Pengelasan (TL)\n2. Memahami dasar hidrolik alat berat, sistem kelistrikan otomotif, dan safety K3\n3. Bersedia ditempatkan di workshop cabang atau area operasional pertambangan",
                    'quota' => 8,
                    'location' => 'Jakarta Timur, DKI Jakarta',
                    'min_salary' => 6000000,
                    'max_salary' => 8200000,
                    'featured' => true,
                    'majors' => ['TKR', 'TP', 'TL'],
                ],
                [
                    'company' => 'PT United Tractors Tbk',
                    'target' => 'class_12_only',
                    'type' => 'internship',
                    'position' => 'Magang Overhaul & Maintenance Workshop',
                    'desc' => 'Membantu proses disassembly dan washing part komponen transmisi alat berat, inspeksi keausan komponen, dan penataan tools workshop.',
                    'qual' => "1. Siswa kelas 12 aktif SMK jurusan Teknik Kendaraan Ringan (TKR) atau Teknik Pemesinan (TP)\n2. Memiliki kemauan belajar tinggi dan fisik prima untuk pekerjaan mekanik berat\n3. Magang bersertifikat industri selama periode 6 bulan",
                    'quota' => 6,
                    'location' => 'Jakarta Timur, DKI Jakarta',
                    'min_salary' => 2700000,
                    'max_salary' => 3700000,
                    'featured' => false,
                    'majors' => ['TKR', 'TP'],
                ],
                [
                    'company' => 'PT United Tractors Tbk',
                    'target' => 'class_12_and_alumni',
                    'type' => 'contract',
                    'position' => 'Warehouse Sparepart & Logistic Officer',
                    'desc' => 'Penerimaan suku cadang alat berat dari vendor, pencatatan stock opname di sistem ERP SAP, penempatan part di rak gudang, dan packing pengiriman.',
                    'qual' => "1. Siswa kelas 12 atau Alumni SMK jurusan TKR / Bisnis Digital (BDP) / TP\n2. Teliti mengelola ribuan part number dan rapi dalam pencatatan stok logistik\n3. Mampu mengoperasikan komputer dan mengoperasikan hand pallet",
                    'quota' => 5,
                    'location' => 'Surabaya, Jawa Timur',
                    'min_salary' => 4700000,
                    'max_salary' => 5900000,
                    'featured' => false,
                    'majors' => ['TKR', 'BDP'],
                ],
                [
                    'company' => 'PT Elektronik Cemerlang',
                    'target' => 'alumni_only',
                    'type' => 'full_time',
                    'position' => 'Teknisi SMT & Assembly Audio Video',
                    'desc' => 'Mengoperasikan mesin otomatis surface mount technology (SMT), reflow oven soldering, serta perbaikan komponen elektronika audio video pabrik.',
                    'qual' => "1. Alumni SMK jurusan Teknik Elektronika Audio Video (TEAV) atau Elektronika Industri (EI)\n2. Mahir membaca skema rangkaian elektronika analog & digital serta teknik solder mikro\n3. Teliti dan memiliki penglihatan mata normal tanpa buta warna",
                    'quota' => 6,
                    'location' => 'Cikarang, Jawa Barat',
                    'min_salary' => 5300000,
                    'max_salary' => 6700000,
                    'featured' => true,
                    'majors' => ['TEAV', 'EI'],
                ],
                [
                    'company' => 'PT Elektronik Cemerlang',
                    'target' => 'class_12_only',
                    'type' => 'internship',
                    'position' => 'Magang Operator Solder & Uji Komponen PCB',
                    'desc' => 'Praktik perakitan komponen elektronika through-hole pada papan sirkuit cetak (PCB), visual inspection sambungan solder timah, dan tes fungsional modul.',
                    'qual' => "1. Siswa aktif kelas 12 SMK jurusan TEAV atau EI\n2. Terampil menggunakan solder listrik timah dan multitester digital\n3. Lokasi magang di kawasan industri Cikarang",
                    'quota' => 10,
                    'location' => 'Cikarang, Jawa Barat',
                    'min_salary' => 2600000,
                    'max_salary' => 3400000,
                    'featured' => false,
                    'majors' => ['TEAV', 'EI'],
                ],
                [
                    'company' => 'PT Elektronik Cemerlang',
                    'target' => 'class_12_and_alumni',
                    'type' => 'contract',
                    'position' => 'Instrumentasi & Kalibrasi Elektronik',
                    'desc' => 'Melakukan kalibrasi sensor temperatur, pressure gauge, sensor optik otomatis, dan pengaturan parameter PLC pengontrol mesin otomatis.',
                    'qual' => "1. Siswa kelas 12 atau Alumni SMK jurusan Elektronika Industri (EI) atau TEAV\n2. Memahami dasar pemrograman ladder PLC dan cara kerja transduser / sensor industri\n3. Bersedia bekerja dengan sistem shift di pabrik Cikarang",
                    'quota' => 5,
                    'location' => 'Cikarang, Jawa Barat',
                    'min_salary' => 4800000,
                    'max_salary' => 6100000,
                    'featured' => false,
                    'majors' => ['EI', 'TEAV'],
                ],
                [
                    'company' => 'PT Multimedia Kreatif',
                    'target' => 'alumni_only',
                    'type' => 'full_time',
                    'position' => 'Junior UI/UX Designer & Web Slicer',
                    'desc' => 'Merancang wireframe, user flow interaktif, dan high-fidelity mockup di Figma, serta konversi desain antarmuka ke kode Tailwind CSS responsif.',
                    'qual' => "1. Khusus Alumni SMK jurusan Rekayasa Perangkat Lunak (RPL) atau Desain Komunikasi Visual (DKV)\n2. Menguasai Figma, design system, typography web, dan dasar kode semantic HTML/CSS\n3. Melampirkan link portofolio desain UI/UX web atau mobile yang pernah dikerjakan",
                    'quota' => 4,
                    'location' => 'Surabaya, Jawa Timur',
                    'min_salary' => 5000000,
                    'max_salary' => 7000000,
                    'featured' => true,
                    'majors' => ['RPL', 'DKV'],
                ],
                [
                    'company' => 'PT Multimedia Kreatif',
                    'target' => 'class_12_only',
                    'type' => 'internship',
                    'position' => 'Magang 2D/3D Asset Animator & Graphic Staff',
                    'desc' => 'Membantu pembuatan aset grafis vektor promosi, ilustrasi karakter 2D, pemodelan objek 3D low-poly sederhana, dan pewarnaan tekstur digital.',
                    'qual' => "1. Siswa kelas 12 aktif SMK jurusan Animasi (NIMA) atau Desain Komunikasi Visual (DKV)\n2. Terbiasa menggunakan Adobe Illustrator, Photoshop, atau Blender 3D\n3. Memiliki kreativitas visual tinggi dan portofolio karya digital",
                    'quota' => 6,
                    'location' => 'Surabaya, Jawa Timur',
                    'min_salary' => 2400000,
                    'max_salary' => 3200000,
                    'featured' => false,
                    'majors' => ['NIMA', 'DKV'],
                ],
                [
                    'company' => 'PT Multimedia Kreatif',
                    'target' => 'class_12_and_alumni',
                    'type' => 'contract',
                    'position' => 'Social Media Content Creator & Video Editor',
                    'desc' => 'Produksi video pendek reels/tiktok untuk branding korporat klien, penulisan storyboard konten, pengambilan footage kamera, dan editing audio video.',
                    'qual' => "1. Siswa kelas 12 atau Alumni SMK jurusan Broadcasting & Perfilman (BP) atau DKV\n2. Menguasai software editing video Premiere Pro, After Effects, atau CapCut desktop\n3. Update terhadap tren konten kreatif visual media sosial terkini",
                    'quota' => 5,
                    'location' => 'Surabaya, Jawa Timur',
                    'min_salary' => 4400000,
                    'max_salary' => 5600000,
                    'featured' => false,
                    'majors' => ['BP', 'DKV'],
                ],
                [
                    'company' => 'PT Petrokimia Gresik',
                    'target' => 'alumni_only',
                    'type' => 'full_time',
                    'position' => 'Junior Welder & Fabrikasi Logam Pabrik',
                    'desc' => 'Melakukan pengelasan sambungan pipa instalasi kimia tekanan tinggi dengan metode SMAW dan GTAW (Argon) serta fabrikasi struktur baja pabrik.',
                    'qual' => "1. Alumni SMK jurusan Teknik Pengelasan (TL) atau Teknik Pemesinan (TP)\n2. Memiliki sertifikat kompetensi las posisi minimal 3G/6G SMAW/GTAW\n3. Taat penuh pada aturan K3 keselamatan kerja area industri kimia berisiko tinggi",
                    'quota' => 5,
                    'location' => 'Gresik, Jawa Timur',
                    'min_salary' => 5800000,
                    'max_salary' => 7800000,
                    'featured' => true,
                    'majors' => ['TL', 'TP'],
                ],
                [
                    'company' => 'PT Petrokimia Gresik',
                    'target' => 'class_12_only',
                    'type' => 'internship',
                    'position' => 'Magang Operator Analis Kimia & Sampling',
                    'desc' => 'Pengambilan sampel bahan baku pupuk dan cairan kimia di instalasi produksi untuk pengujian parameter pH, kadar air, dan densitas di lab quality.',
                    'qual' => "1. Siswa aktif kelas 12 SMK jurusan Teknik Kimia Industri (KL)\n2. Memahami teknik dasar titrasi laboratorium, penimbangan analitik, dan SOP keselamatan bahan B3\n3. Penempatan magang selama 6 bulan di kompleks pabrik Gresik",
                    'quota' => 6,
                    'location' => 'Gresik, Jawa Timur',
                    'min_salary' => 2600000,
                    'max_salary' => 3500000,
                    'featured' => false,
                    'majors' => ['KL'],
                ],
                [
                    'company' => 'PT Petrokimia Gresik',
                    'target' => 'class_12_and_alumni',
                    'type' => 'contract',
                    'position' => 'Teknisi Pemeliharaan Pompa & Mesin Industri',
                    'desc' => 'Perawatan berkala pompa sentrifugal kimia, kompresor udara industri, penggantian mechanical seal, bearing, dan alignment poros motor penggerak.',
                    'qual' => "1. Siswa kelas 12 atau Alumni SMK jurusan Teknik Pemesinan (TP) atau Teknik Kendaraan Ringan (TKR)\n2. Memahami cara kerja mesin fluida mekanik, pembongkaran transmisi roda gigi, dan greasing\n3. Tidak takut bekerja di area instalasi pabrik dan siap siaga dalam tim maintenance",
                    'quota' => 6,
                    'location' => 'Gresik, Jawa Timur',
                    'min_salary' => 4900000,
                    'max_salary' => 6200000,
                    'featured' => false,
                    'majors' => ['TP', 'TKR'],
                ],
            ];

            foreach ($vacancies as $item) {
                $companyId = $companies->get($item['company']);
                if (! $companyId) {
                    continue;
                }

                $shortCompany = str_replace('PT ', '', $item['company']);
                $slug = Str::slug($item['position'].'-'.Str::limit($shortCompany, 20, ''));
                $targetId = $targets->get($item['target']);
                $typeId = $types->get($item['type']);

                $vacancy = JobVacancy::updateOrCreate(
                    ['slug' => $slug],
                    [
                        'company_id' => $companyId,
                        'job_type_id' => $typeId,
                        'status_id' => $statusPublished?->id,
                        'target_applicant_id' => $targetId,
                        'title' => 'Lowongan '.$item['position'],
                        'slug' => $slug,
                        'position' => $item['position'],
                        'description' => $item['desc'],
                        'qualification' => $item['qual'],
                        'quota' => $item['quota'],
                        'deadline' => '2026-12-31',
                        'work_location' => $item['location'],
                        'min_salary' => $item['min_salary'],
                        'max_salary' => $item['max_salary'],
                        'is_featured' => $item['featured'] ?? false,
                        'is_active' => true,
                        'created_by' => $creatorId,
                        'updated_by' => $creatorId,
                    ]
                );

                $majorIds = [];
                foreach ($item['majors'] as $code) {
                    if ($majorMap->has($code)) {
                        $majorIds[] = $majorMap->get($code)->id;
                    }
                }

                if (! empty($majorIds)) {
                    $vacancy->majors()->sync($majorIds);
                }
            }

            JobVacancy::where('is_active', true)
                ->where('deadline', '<', now()->toDateString())
                ->update(['deadline' => '2026-12-31']);
        });
    }
}
